name: access-token-management/ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/access-token-management-**
      - .github/workflows/ci-template.yml
      - access-token-management/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props
  pull_request:
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/access-token-management-**
      - .github/workflows/ci-template.yml
      - access-token-management/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props

jobs:
  build:
    uses: ./.github/workflows/ci-template.yml
    with:
      product: access-token-management
      test-targets: '["test"]'
