name: identity-model-oidc-client/publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/identity-model-oidc-client-**
      - .github/workflows/publish-template.yml
      - identity-model-oidc-client/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props

jobs:
  publish:
    uses: ./.github/workflows/publish-template.yml
    with:
      product: identity-model-oidc-client
      solution: identity-model-oidc-client/identity-model-oidc-client.slnf
    secrets:
      SignClientSecret: ${{ secrets.SignClientSecret }}
