name: identity-model-oidc-client/ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/identity-model-oidc-client-**
      - .github/workflows/ci-template.yml
      - identity-model-oidc-client/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props
  pull_request:
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/identity-model-oidc-client-**
      - .github/workflows/ci-template.yml
      - identity-model-oidc-client/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props

jobs:
  build:
    uses: ./.github/workflows/ci-template.yml
    with:
      product: identity-model-oidc-client
      test-targets: '["test"]'
