name: introspection/publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/introspection-**
      - .github/workflows/publish-template.yml
      - introspection/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props

jobs:
  publish:
    uses: ./.github/workflows/publish-template.yml
    with:
      product: introspection
      solution: introspection/introspection.slnf
    secrets:
      SignClientSecret: ${{ secrets.SignClientSecret }}
