name: razor-slices/publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - .config/dotnet-tools.json
      - .github/BuildHelpers/**
      - .github/workflows/razor-slices-**
      - .github/workflows/publish-template.yml
      - razor-slices/**
      - .editorconfig
      - Directory.Packages.props
      - global.json
      - src.props
      - test.props

jobs:
  publish:
    uses: ./.github/workflows/publish-template.yml
    with:
      product: razor-slices
      solution: razor-slices/razor-slices.slnf
    secrets:
      SignClientSecret: ${{ secrets.SignClientSecret }}
